### ISSUE TITLE
Game checklist

### ISSUE THREAD

**Issue by lectri** [lectri/MineSweeper#1]
These are a list of things that must be finished to create a release for this game

- [x] Add buttons to screen
- [ ] Add bombs to buttons
- [ ] Show how many bombs a player is adjacent to
- [ ] Add marker functionality
- [ ] Allow replaying
- [ ] Win screen and lose screen
